changelog:
  categories:
    - title: Research
      labels:
        - research

    - title: Reproducibility
      labels:
        - reproducibility

    - title: Fixes
      labels:
        - bug

    - title: Other Changes
      labels:
        - "*"
